apiVersion: apps/v1
kind: Deployment
metadata:
  name: documenthor
  namespace: prow
  labels:
    app: documenthor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documenthor
  template:
    metadata:
      annotations:
        fluentbit.io/parser: json_iso
      labels:
        app: documenthor
    spec:
      terminationGracePeriodSeconds: 180
      containers:
        - name: documenthor
          image: quay.io/kubermatic/documenthor:v0.0.2
          imagePullPolicy: IfNotPresent
          args:
            - -dry-run=false
            - -github-token-path=/etc/github/token
            - -github-endpoint=http://ghproxy
            - -github-endpoint=https://api.github.com
          ports:
            - name: http
              containerPort: 8888
          volumeMounts:
            - name: hmac
              mountPath: /etc/webhook
              readOnly: true
            - name: oauth
              mountPath: /etc/github
              readOnly: true
      volumes:
        - name: hmac
          secret:
            secretName: hmac-token
        - name: oauth
          secret:
            secretName: oauth-org-ro-token
---
apiVersion: v1
kind: Service
metadata:
  name: documenthor
  namespace: prow
spec:
  selector:
    app: documenthor
  ports:
    - port: 80
      targetPort: 8888
